publicHoistPattern:
  - '@commitlint/*'
packages:
  - app
  - internal/*
  - internal/lint-configs/*
  - scripts/*
  - packages/*
  - packages/@core/*
  - packages/@core/base/*
  - packages/effects/*
catalog:
  '@antfu/eslint-config': ^9.0.0
  '@clack/prompts': ^1.4.0
  '@commitlint/cli': ^21.0.1
  '@commitlint/config-conventional': ^21.0.1
  '@manypkg/get-packages': ^3.1.0
  '@pnpm/workspace.read-manifest': ^1000.3.1
  '@tailwindcss/vite': ^4.3.0
  '@types/node': ^25.9.1
  '@vitejs/plugin-vue': ^6.0.6
  '@vitejs/plugin-vue-jsx': ^5.1.5
  '@vue/shared': ^3.5.35
  '@vue/tsconfig': ^0.9.1
  cac: ^7.0.0
  commitlint-plugin-function-rules: ^5.0.1
  consola: ^3.4.2
  dayjs: ^1.11.21
  dotenv: ^17.4.2
  eslint: ^10.3.0
  execa: ^9.6.1
  happy-dom: ^20.9.0
  lefthook: ^2.1.8
  pkg-types: ^2.3.1
  pnpm-workspace-yaml: ^1.6.0
  sass-embedded: ^1.100.0
  tsdown: ^0.22.0
  turbo: ^2.9.14
  typescript: ~6.0.2
  unplugin-dts: ^1.0.1
  vite: ^8.0.13
  vite-plugin-pwa: ^0.20.0
  vitest: ^4.1.7
  vue: ^3.5.34
  vue-tsc: ^3.2.8
